name: Mobile + Release
on: workflow_dispatch
jobs:
  Mobile:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-14]
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.7

      - name: Install Libraries
        run: |
          haxelib git hxcpp https://github.com/th2l-devs/hxcpp --quiet
          haxelib git lime https://github.com/th2l-devs/lime --quiet
          haxelib git openfl https://github.com/th2l-devs/openfl --quiet
          haxelib git flixel https://github.com/HomuHomu833/flixel --quiet
          haxelib install flixel-addons 3.3.2 --quiet
          haxelib install flixel-tools 1.5.1 --quiet
          haxelib git SScript https://github.com/th2l-devs/SScript --quiet
          haxelib install tjson 1.4.0 --quiet
          haxelib git flxanimate https://github.com/Dot-Stuff/flxanimate 768740a56b26aa0c072720e0d1236b94afe68e3e --quiet
          if [[ "${{ runner.os }}" == "macOS" ]] ; then
            haxelib git linc_luajit https://github.com/th2l-devs/linc_luajit --quiet
          else
            haxelib git linc_luajit https://github.com/kittycathy233/linc_luajit --quiet --skip-dependencies
          fi
          haxelib git hxdiscord_rpc https://github.com/MAJigsaw77/hxdiscord_rpc 3538a1c2bb07b04208cd014220207f8173acdb21 --quiet --skip-dependencies
          haxelib git hxvlc https://github.com/th2l-devs/hxvlc --quiet --skip-dependencies
          haxelib git funkin.vis https://github.com/FunkinCrew/funkVis d5361037efa3a02c4ab20b5bd14ca11e7d00f519 --quiet --skip-dependencies
          haxelib git grig.audio https://gitlab.com/haxe-grig/grig.audio.git cbf91e2180fd2e374924fe74844086aab7891666 --quiet
    #      haxelib git extension-androidtools https://github.com/MAJigsaw77/extension-androidtools 727693f0a76c6e396df675bb0ed95d7639a4db01 --quiet --skip-dependencies

      - name: Configure Android
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_LATEST_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME_17_X64
          haxelib run lime config ANDROID_SETUP true

      - name: Compile (Android)
        if: startsWith(matrix.os, 'ubuntu')
        run: haxelib run lime build android -D officialBuild

      - name: Compile (iOS)
        if: startsWith(matrix.os, 'macos')
        run: haxelib run lime build ios -nosign -D officialBuild

      - name: Make Ipa And Zip For Release
        if: startsWith(matrix.os, 'macos')
        run: |
          cd export/release/ios/build/*-iphoneos
          mkdir Payload
          mv *.app Payload
          zip -r PsychEngine.ipa Payload

      - name: Upload Artifact (Android)
        if: startsWith(matrix.os, 'ubuntu')
        uses: actions/upload-artifact@main
        with:
          name: androidBuild
          path: export/release/android/bin/app/build/outputs/apk/release/*.apk
          if-no-files-found: error

      - name: Upload Artifact (iOS)
        if: startsWith(matrix.os, 'macos')
        uses: actions/upload-artifact@main
        with:
          name: iOSBuild
          path: export/release/ios/build/Release-iphoneos/*.ipa
          if-no-files-found: error
  Releaser:
    needs: [Mobile]
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Download Android Build
        uses: actions/download-artifact@main
        with:
           name: androidBuild
           path: /home/runner

      - name: Move Android File
        run: mv /home/runner/PsychEngine-release.apk /home/runner/PsychEngine-Android.apk

      - name: Download iOS Build
        uses: actions/download-artifact@main
        with:
           name: iOSBuild
           path: /home/runner

      - name: Publish The Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          release: true
          automatic_release_tag: "1.0-prerelease"
          title: "1.0 (Prerelease)"
          files: |
            /home/runner/*.apk
            /home/runner/*.ipa
